namespace Smart.IO.ByteMapper.AspNetCore.Generator;

using System.Text;

using Smart.IO.ByteMapper.AspNetCore.Generator.Models;

using SourceGenerateHelper;

// Emit stage: turns EndpointModel records into the binding factory partial class, the assembly
// bootstrap, and the AddByteMapperFormatters extension. Pure string generation with no Roslyn
// dependency, so it can be unit-tested by constructing models directly.
internal static class ByteMapperAspNetCoreSourceBuilder
{
    // Builds the per-class binding factory method(s) for a single endpoint binding.
    public static void BuildBinding(SourceBuilder builder, EndpointModel ep)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(ep.Namespace))
        {
            builder.Namespace(ep.Namespace);
            builder.NewLine();
        }

        builder.Indent().Append("partial class ").Append(ep.ClassName).NewLine();
        builder.BeginScope();

        // Single binding factory
        builder.Indent()
            .Append("public static global::Smart.IO.ByteMapper.AspNetCore.ByteMapperBinding<").Append(ep.EntityTypeFqn).Append("> ").Append(ep.FactoryMethodName).Append("()")
            .NewLine();
        builder.Indent().Append("    => new(").NewLine();
        builder.Indent().Append("        size: ").Append(ep.Size.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(",").NewLine();
        builder.Indent().Append("        read:    static (s, t) => ").Append(ep.ReaderMethodName).Append("(s, t),").NewLine();
        builder.Indent().Append("        write:   static (s, d) => ").Append(ep.WriterMethodName).Append("(d, s),").NewLine();
        builder.Indent().Append("        factory: static () => new ").Append(ep.EntityTypeFqn).Append("());").NewLine();

        if (ep.GenerateArrayBinding)
        {
            builder.NewLine();

            // Array binding factory
            builder.Indent()
                .Append("public static global::Smart.IO.ByteMapper.AspNetCore.ByteMapperArrayBinding<").Append(ep.EntityTypeFqn).Append("> ").Append(ep.ArrayFactoryMethodName).Append("()")
                .NewLine();
            builder.Indent().Append("    => new(").NewLine();
            builder.Indent().Append("        elementSize:  ").Append(ep.Size.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(",").NewLine();
            builder.Indent().Append("        readElement:  static (s, t) => ").Append(ep.ReaderMethodName).Append("(s, t),").NewLine();
            builder.Indent().Append("        writeElement: static (s, d) => ").Append(ep.WriterMethodName).Append("(d, s),").NewLine();
            builder.Indent().Append("        factory:      static () => new ").Append(ep.EntityTypeFqn).Append("());").NewLine();
        }

        builder.EndScope();
    }

    // Builds the assembly-level registry bootstrap and the AddByteMapperFormatters extension.
    public static void BuildBootstrap(SourceBuilder builder, IReadOnlyList<EndpointModel> endpoints)
    {
        var rootNs = string.Empty;
        foreach (var e in endpoints)
        {
            if (!String.IsNullOrEmpty(e.RootNamespace))
            {
                rootNs = e.RootNamespace;
                break;
            }
        }
        if (String.IsNullOrEmpty(rootNs))
        {
            rootNs = "ByteMapperGenerated";
        }

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();
        builder.Namespace(rootNs);
        builder.NewLine();
        builder.Indent().Append("using System.Collections.Generic;").NewLine();
        builder.NewLine();

        // Bootstrap class
        builder.Indent().Append("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]").NewLine();
        builder.Indent().Append("internal static class __ByteMapperAspNetCoreBootstrap").NewLine();
        builder.BeginScope();

        builder.Indent().Append("public static global::Smart.IO.ByteMapper.AspNetCore.ByteMapperRegistry Build()").NewLine();
        builder.BeginScope();

        builder.Indent().Append("var single = new Dictionary<(global::System.Type, global::System.Type?), global::Smart.IO.ByteMapper.AspNetCore.ByteMapperBinding>").NewLine();
        builder.Indent().Append("{").NewLine();
        foreach (var ep in endpoints)
        {
            var qualifiedClass = String.IsNullOrEmpty(ep.Namespace)
                ? $"global::{ep.ClassName}"
                : $"global::{ep.Namespace}.{ep.ClassName}";
            var profileLiteral = ep.ProfileTypeFqn is null ? "null" : $"typeof({ep.ProfileTypeFqn})";
            builder.Indent().Append("    { (typeof(").Append(ep.EntityTypeFqn).Append("), ").Append(profileLiteral).Append("), ").Append(qualifiedClass).Append(".").Append(ep.FactoryMethodName).Append("() },").NewLine();
        }
        builder.Indent().Append("};").NewLine();
        builder.NewLine();

        builder.Indent().Append("var array = new Dictionary<(global::System.Type, global::System.Type?), object>").NewLine();
        builder.Indent().Append("{").NewLine();
        foreach (var ep in endpoints)
        {
            if (!ep.GenerateArrayBinding)
            {
                continue;
            }

            var qualifiedClass = String.IsNullOrEmpty(ep.Namespace)
                ? $"global::{ep.ClassName}"
                : $"global::{ep.Namespace}.{ep.ClassName}";
            var profileLiteral = ep.ProfileTypeFqn is null ? "null" : $"typeof({ep.ProfileTypeFqn})";
            builder.Indent().Append("    { (typeof(").Append(ep.EntityTypeFqn).Append("), ").Append(profileLiteral).Append("), ").Append(qualifiedClass).Append(".").Append(ep.ArrayFactoryMethodName).Append("() },").NewLine();
        }
        builder.Indent().Append("};").NewLine();
        builder.NewLine();

        builder.Indent().Append("return new global::Smart.IO.ByteMapper.AspNetCore.ByteMapperRegistry(single, array);").NewLine();
        builder.EndScope();

        builder.EndScope();
        builder.NewLine();

        // AddByteMapperFormatters extension
        builder.Indent().Append("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]").NewLine();
        builder.Indent().Append("internal static class __ByteMapperServiceCollectionExtensions").NewLine();
        builder.BeginScope();

        builder.Indent().Append("// Registers ByteMapper registry, formatters, and options. Generated by source generator.").NewLine();
        builder.Indent().Append("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddByteMapperFormatters(").NewLine();
        builder.Indent().Append("    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,").NewLine();
        builder.Indent().Append("    global::System.Action<global::Smart.IO.ByteMapper.AspNetCore.ByteMapperFormatterOptions>? configure = null)").NewLine();
        builder.Indent().Append("    => global::Smart.IO.ByteMapper.AspNetCore.ByteMapperServiceCollectionExtensions.AddByteMapperFormatters(").NewLine();
        builder.Indent().Append("        services,").NewLine();
        builder.Indent().Append("        __ByteMapperAspNetCoreBootstrap.Build(),").NewLine();
        builder.Indent().Append("        configure);").NewLine();

        builder.EndScope();
    }

    // Source file name (without extension) for an endpoint binding; profile name disambiguates
    // multiple bindings declared on the same class.
    public static string MakeFilename(string ns, string className, string? profileFqn)
    {
        var buffer = new StringBuilder();
        if (!String.IsNullOrEmpty(ns))
        {
            buffer.Append(ns.Replace('.', '_'));
            buffer.Append('_');
        }
        buffer.Append(className.Replace('<', '[').Replace('>', ']'));
        if (!String.IsNullOrEmpty(profileFqn))
        {
            var lastDot = profileFqn!.LastIndexOf('.');
            var shortName = lastDot >= 0 ? profileFqn.Substring(lastDot + 1) : profileFqn;
            buffer.Append('_').Append(shortName);
        }
        return buffer.ToString();
    }
}
