namespace Smart.IO.ByteMapper.AspNetCore.Generator;

using Smart.IO.ByteMapper.AspNetCore.Generator.Models;

using SourceGenerateHelper;

// Emit stage: turns EndPointModel records into the binding factory partial class, the assembly
// bootstrap, and the AddByteMapperFormatters extension. Pure string generation with no Roslyn
// dependency, so it can be unit-tested by constructing models directly.
internal static class ByteMapperAspNetCoreSourceBuilder
{
    // Factory method names derived from the disambiguating suffix. / 識別子サフィックスからファクトリ名を導出する。
    private static string SingleFactoryName(EndPointModel ep) => "CreateByteMapperBinding" + ep.NameSuffix;

    private static string ArrayFactoryName(EndPointModel ep) => "CreateByteMapperArrayBinding" + ep.NameSuffix;

    private static string FactoryAccessibility(EndPointModel ep) => ep.IsEntityPublic ? "public" : "internal";

    private static string WriteCall(EndPointModel ep, string source, string destination) =>
        ep.WriterReturnsArray
            ? $"global::System.MemoryExtensions.CopyTo({ep.WriterMethodName}({source}), {destination})"
            : $"{ep.WriterMethodName}({destination}, {source})";

    // Builds the per-class binding factory method(s) for a single endPoint binding.
    public static void BuildBinding(SourceBuilder builder, EndPointModel ep)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Disable("CS0612, CS0618");
        builder.NewLine();

        if (!String.IsNullOrEmpty(ep.Namespace))
        {
            builder.Namespace(ep.Namespace);
            builder.NewLine();
        }

        foreach (var containingType in ep.ContainingTypes)
        {
            builder.Indent().Append(containingType).NewLine();
            builder.BeginScope();
        }

        // Single binding factory
        builder.Indent()
            .Append(FactoryAccessibility(ep)).Append(" static global::Smart.IO.ByteMapper.AspNetCore.ByteMapperBinding<").Append(ep.EntityTypeFqn).Append("> ").Append(SingleFactoryName(ep)).Append("()")
            .NewLine();
        builder.Indent().Append("    => new(").NewLine();
        builder.Indent().Append("        size: ").Append(ep.Size.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(",").NewLine();
        builder.Indent().Append("        read:    static (s, t) => ").Append(ep.ReaderMethodName).Append("(s, t),").NewLine();
        builder.Indent().Append("        write:   static (s, d) => ").Append(WriteCall(ep, "s", "d")).Append(",").NewLine();
        builder.Indent().Append("        factory: static () => new ").Append(ep.EntityTypeFqn).Append("());").NewLine();

        if (ep.GenerateArrayBinding)
        {
            builder.NewLine();

            // Array binding factory
            builder.Indent()
                .Append(FactoryAccessibility(ep)).Append(" static global::Smart.IO.ByteMapper.AspNetCore.ByteMapperArrayBinding<").Append(ep.EntityTypeFqn).Append("> ").Append(ArrayFactoryName(ep)).Append("()")
                .NewLine();
            builder.Indent().Append("    => new(").NewLine();
            builder.Indent().Append("        elementSize:  ").Append(ep.Size.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(",").NewLine();
            builder.Indent().Append("        readElement:  static (s, t) => ").Append(ep.ReaderMethodName).Append("(s, t),").NewLine();
            builder.Indent().Append("        writeElement: static (s, d) => ").Append(WriteCall(ep, "s", "d")).Append(",").NewLine();
            builder.Indent().Append("        factory:      static () => new ").Append(ep.EntityTypeFqn).Append("());").NewLine();
        }

        for (var i = 0; i < ep.ContainingTypes.Count; i++)
        {
            builder.EndScope();
        }
    }

    // Builds the assembly-level registry bootstrap and the AddByteMapperFormatters extension.
    public static void BuildBootstrap(SourceBuilder builder, IReadOnlyList<EndPointModel> endPoints)
    {
        var rootNs = string.Empty;
        foreach (var e in endPoints)
        {
            if (!String.IsNullOrEmpty(e.RootNamespace))
            {
                rootNs = e.RootNamespace;
                break;
            }
        }
        if (String.IsNullOrEmpty(rootNs))
        {
            rootNs = "ByteMapperGenerated";
        }

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Disable("CS0612, CS0618");
        builder.NewLine();
        builder.Namespace(rootNs);
        builder.NewLine();

        // Bootstrap class
        builder.Indent().Append("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]").NewLine();
        builder.Indent().Append("internal static class __ByteMapperAspNetCoreBootstrap").NewLine();
        builder.BeginScope();

        builder.Indent().Append("public static global::Smart.IO.ByteMapper.AspNetCore.ByteMapperRegistry Build()").NewLine();
        builder.BeginScope();

        builder.Indent().Append("var single = new global::System.Collections.Generic.Dictionary<(global::System.Type, global::System.Type?), global::Smart.IO.ByteMapper.AspNetCore.ByteMapperBinding>").NewLine();
        builder.Indent().Append("{").NewLine();
        foreach (var ep in endPoints)
        {
            var qualifiedClass = ep.ClassFullName;
            var profileLiteral = ep.ProfileTypeFqn is null ? "null" : $"typeof({ep.ProfileTypeFqn})";
            builder.Indent().Append("    { (typeof(").Append(ep.EntityTypeFqn).Append("), ").Append(profileLiteral).Append("), ").Append(qualifiedClass).Append(".").Append(SingleFactoryName(ep)).Append("() },").NewLine();
        }
        builder.Indent().Append("};").NewLine();
        builder.NewLine();

        builder.Indent().Append("var array = new global::System.Collections.Generic.Dictionary<(global::System.Type, global::System.Type?), object>").NewLine();
        builder.Indent().Append("{").NewLine();
        foreach (var ep in endPoints)
        {
            if (!ep.GenerateArrayBinding)
            {
                continue;
            }

            var qualifiedClass = ep.ClassFullName;
            var profileLiteral = ep.ProfileTypeFqn is null ? "null" : $"typeof({ep.ProfileTypeFqn})";
            builder.Indent().Append("    { (typeof(").Append(ep.EntityTypeFqn).Append("), ").Append(profileLiteral).Append("), ").Append(qualifiedClass).Append(".").Append(ArrayFactoryName(ep)).Append("() },").NewLine();
        }
        builder.Indent().Append("};").NewLine();
        builder.NewLine();

        builder.Indent().Append("return new global::Smart.IO.ByteMapper.AspNetCore.ByteMapperRegistry(single, array);").NewLine();
        builder.EndScope();

        builder.EndScope();
        builder.NewLine();

        // AddByteMapperFormatters extension
        builder.Indent().Append("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]").NewLine();
        builder.Indent().Append("internal static class __ByteMapperServiceCollectionExtensions").NewLine();
        builder.BeginScope();

        builder.Indent().Append("// Registers ByteMapper registry, formatters, and options. Generated by source generator.").NewLine();
        builder.Indent().Append("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddByteMapperFormatters(").NewLine();
        builder.Indent().Append("    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,").NewLine();
        builder.Indent().Append("    global::System.Action<global::Smart.IO.ByteMapper.AspNetCore.ByteMapperFormatterOptions>? configure = null)").NewLine();
        builder.Indent().Append("    => global::Smart.IO.ByteMapper.AspNetCore.ByteMapperServiceCollectionExtensions.AddByteMapperFormatters(").NewLine();
        builder.Indent().Append("        services,").NewLine();
        builder.Indent().Append("        __ByteMapperAspNetCoreBootstrap.Build(),").NewLine();
        builder.Indent().Append("        configure);").NewLine();

        builder.EndScope();
    }
}
