namespace Smart.IO.ByteMapper.Generator;

using System;
using System.Collections.Generic;
using System.Linq;

using Smart.IO.ByteMapper.Generator.Models;

using SourceGenerateHelper;

// Emit stage: turns the equatable MapperMethodModel records of one partial class into C# source.
// Pure string generation with no Roslyn dependency, so it can be unit-tested by constructing models
// directly. Input models are assumed valid (validation happens in ByteMapperModelBuilder).
internal static class ByteMapperSourceBuilder
{
    // Builds the partial class source for all mapper methods declared in a single class.
    public static void Build(SourceBuilder builder, IReadOnlyList<MapperMethodModel> methods)
    {
        var numberedMethods = AssignConverterFieldNames(methods);

        var first = numberedMethods[0];

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Disable("CS0612, CS0618");
        builder.NewLine();

        if (!String.IsNullOrEmpty(first.Namespace))
        {
            builder.Namespace(first.Namespace);
            builder.NewLine();
        }

        foreach (var containingType in first.ContainingTypes)
        {
            builder.Indent().Append(containingType).NewLine();
            builder.BeginScope();
        }

        // Emit all converter fields first, skipping already-emitted deduplicated fields / 最初にすべてのコンバーターフィールドを出力する（重複排除済みフィールドはスキップ）
        var emittedFields = new HashSet<string>(StringComparer.Ordinal);
        foreach (var method in numberedMethods)
        {
            foreach (var member in method.Members)
            {
                if (!emittedFields.Add(member.Converter.FieldName))
                {
                    continue;
                }
                builder.Indent()
                    .Append("// [")
                    .Append(member.PropertyName)
                    .Append("] offset=")
                    .Append(member.Offset.ToString(System.Globalization.CultureInfo.InvariantCulture))
                    .NewLine();
                builder.Indent()
                    .Append("private static readonly ")
                    .Append(member.Converter.ConverterTypeFqn)
                    .Append(" ")
                    .Append(member.Converter.FieldName)
                    .Append(" = new(")
                    .Append(String.Join(", ", member.Converter.CtorArgExpressions))
                    .Append(");")
                    .NewLine();
            }
        }

        // Emit static readonly fields for MapConstant byte arrays to avoid per-call heap allocation.
        // Key: hex-literal CSV of bytes; Value: generated field name / MapConstant バイト配列を静的フィールドとして出力し、Write のたびのヒープ割り当てを回避する
        var constantFieldMap = new Dictionary<string, string>(StringComparer.Ordinal);
        var constantCounter = 0;
        foreach (var method in numberedMethods)
        {
            foreach (var tm in method.TypeMappings)
            {
                if (tm.Kind != TypeMappingKind.Constant)
                {
                    continue;
                }
                var key = String.Join(", ", tm.Constant.Select(b => $"0x{b:X2}"));
                if (!constantFieldMap.ContainsKey(key))
                {
                    var fieldName = $"__ConstantBytes{constantCounter++}";
                    constantFieldMap[key] = fieldName;
                    builder.Indent()
                        .Append($"private static readonly byte[] {fieldName} = [{key}];")
                        .NewLine();
                }
            }
        }

        // Emit methods / メソッド本体を出力する
        var methodFirst = true;
        foreach (var method in numberedMethods)
        {
            if (!methodFirst)
            {
                builder.NewLine();
            }
            methodFirst = false;

            builder.NewLine();
            EmitMethod(builder, method, constantFieldMap);
        }

        for (var i = 0; i < first.ContainingTypes.Count; i++)
        {
            builder.EndScope();
        }
    }

    // Assigns deduplicated converter field names within the class / クラス内でコンバーターフィールド名を重複排除しながら割り当てる
    // Methods targeting the same type with identical converter configs share one static field instance.
    // ReSharper disable once ParameterTypeCanBeEnumerable.Local
    private static List<MapperMethodModel> AssignConverterFieldNames(IReadOnlyList<MapperMethodModel> methods)
    {
        var converterFieldMap = new Dictionary<string, string>(StringComparer.Ordinal);
        var fieldCounter = 0;
        var numberedMethods = new List<MapperMethodModel>();
        foreach (var m in methods)
        {
            // Assign a shared field name per unique (targetType, memberIndex, converterType, ctorArgs) key
            var fixedMembers = m.Members.Select((member, pi) =>
            {
                var key = $"{m.TargetTypeFqn}|{pi}|{member.Converter.ConverterTypeFqn}|{String.Join(",", member.Converter.CtorArgExpressions)}";
                if (!converterFieldMap.TryGetValue(key, out var fieldName))
                {
                    fieldName = $"__Converter{fieldCounter++}";
                    converterFieldMap[key] = fieldName;
                }
                return member with { Converter = member.Converter with { FieldName = fieldName } };
            }).ToArray();
            numberedMethods.Add(m with
            {
                Members = [with(fixedMembers)]
            });
        }

        return numberedMethods;
    }

    private static void EmitMethod(SourceBuilder builder, MapperMethodModel method, IReadOnlyDictionary<string, string> constantFieldMap)
    {
        if (method.IsFallback)
        {
            builder.Indent().Append(method.Signature).NewLine();
            builder.BeginScope();
            builder.Indent().Append("throw new global::System.InvalidOperationException();").NewLine();
            builder.EndScope();
            return;
        }

        if (!method.HasMethodImpl)
        {
            builder.Indent()
                .Append("[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]")
                .NewLine();
        }

        builder.Indent().Append(method.Signature).NewLine();

        switch (method.Shape)
        {
            case MapperShape.InPlace:
                builder.BeginScope();
                foreach (var member in method.Members)
                {
                    EmitReadMember(builder, member, method.BufferParamName, method.TargetParamName);
                }
                builder.EndScope();
                break;

            case MapperShape.NewInstance:
                builder.BeginScope();
                builder.Indent()
                    .Append("var ").Append(method.TargetParamName).Append(" = new ").Append(method.TargetTypeFqn).Append("();")
                    .NewLine();
                foreach (var member in method.Members)
                {
                    EmitReadMember(builder, member, method.BufferParamName, method.TargetParamName);
                }
                builder.Indent().Append("return ").Append(method.TargetParamName).Append(";").NewLine();
                builder.EndScope();
                break;

            case MapperShape.WriteSpan:
                builder.BeginScope();
                EmitWriteBody(builder, method, method.BufferParamName, constantFieldMap);
                builder.EndScope();
                break;

            case MapperShape.WriteAlloc:
                builder.BeginScope();
                builder.Indent()
                    .Append($"var {method.BufferParamName} = new byte[{method.Size}];")
                    .NewLine();
                builder.Indent()
                    .Append($"var __span = (global::System.Span<byte>){method.BufferParamName};")
                    .NewLine();
                EmitWriteBody(builder, method, "__span", constantFieldMap);
                builder.Indent().Append("return ").Append(method.BufferParamName).Append(";").NewLine();
                builder.EndScope();
                break;
        }
    }

    private static void EmitReadMember(SourceBuilder builder, MemberMappingModel member, string bufferParam, string targetParam)
    {
        var size = ResolveSizeExpression(member);

        builder.Indent()
            .Append(targetParam).Append(".")
            .Append(CSharpIdentifier.Escape(member.PropertyName))
            .Append(" = ")
            .Append(member.Converter.FieldName)
            .Append(".Read(").Append(bufferParam).Append(".Slice(")
            .Append($"{member.Offset}")
            .Append(", ")
            .Append(size)
            .Append(member.ReadValueOrDefault ? ")).GetValueOrDefault();" : "));")
            .NewLine();
    }

    private static void EmitWriteBody(SourceBuilder builder, MapperMethodModel method, string spanVarName, IReadOnlyDictionary<string, string> constantFieldMap)
    {
        // Write constants/fillers / 定数・フィラーを書き込む
        foreach (var tm in method.TypeMappings)
        {
            if (tm.Kind == TypeMappingKind.Filler)
            {
                builder.Indent()
                    .Append($"{spanVarName}.Slice({tm.Offset}, {tm.Size}).Fill((byte)0x{tm.Filler:X2});")
                    .NewLine();
            }
            else if (tm.Kind == TypeMappingKind.Constant)
            {
                // Use the pre-declared static field to avoid per-call heap allocation.
                var key = String.Join(", ", tm.Constant.Select(b => $"0x{b:X2}"));
                var fieldName = constantFieldMap[key];
                builder.Indent()
                    .Append($"new global::System.ReadOnlySpan<byte>({fieldName}).CopyTo({spanVarName}.Slice({tm.Offset}, {tm.Size}));")
                    .NewLine();
            }
        }

        foreach (var member in method.Members)
        {
            var size = ResolveSizeExpression(member);

            builder.Indent()
                .Append(member.Converter.FieldName)
                .Append($".Write({spanVarName}.Slice(")
                .Append($"{member.Offset}")
                .Append(", ")
                .Append(size)
                .Append("), ").Append(method.TargetParamName).Append(".")
                .Append(CSharpIdentifier.Escape(member.PropertyName))
                .Append(");")
                .NewLine();
        }
    }

    // Resolves the byte-length expression for a converter call. / コンバーター呼び出しのバイト長式を解決する。
    private static string ResolveSizeExpression(MemberMappingModel member)
    {
        if (member.Converter.SizeKind == SizeKind.Const)
        {
            return $"{member.Converter.ConstSize!.Value}";
        }
        if (member.Converter.SizeKind == SizeKind.StaticMember)
        {
            return $"{member.Converter.ConverterTypeFqn}.Size";
        }
        if (member.Converter.ConstSize.HasValue)
        {
            return $"{member.Converter.ConstSize.Value}";
        }
        return $"{member.Converter.FieldName}.Size";
    }
}
